import Head from 'next/head'
import { useRouter } from 'next/router'

export default function Terms() {
  const router = useRouter()
  return (
    <>
      <Head><title>Terms of Service — LandlordAI</title></Head>
      <nav style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '1rem 2rem', borderBottom: '1px solid var(--border)' }}>
        <div className="logo" onClick={() => router.push('/')} style={{ cursor: 'pointer' }}>🏠 Landlord<em>AI</em></div>
      </nav>
      <div className="legal">
        <h1>Terms of Service</h1>
        <div className="date">Last updated: June 2026</div>
        <h2>1. Acceptance of Terms</h2>
        <p>By using LandlordAI, you agree to these terms. If you do not agree, please do not use our service.</p>
        <h2>2. Description of Service</h2>
        <p>LandlordAI provides AI-generated document templates and writing assistance for landlords and property managers. Our tools generate drafts only and are not legal advice.</p>
        <h2>3. Not Legal Advice</h2>
        <p>All content generated by LandlordAI is for informational purposes only. It does not constitute legal advice. Always consult a qualified attorney before using any legal document, especially for eviction notices or lease agreements. Laws vary by state and locality.</p>
        <h2>4. User Responsibilities</h2>
        <ul>
          <li>You are responsible for reviewing all generated content before use</li>
          <li>You must comply with all applicable fair housing laws</li>
          <li>You may not use our service for illegal purposes</li>
          <li>You are responsible for the accuracy of information you provide</li>
        </ul>
        <h2>5. Intellectual Property</h2>
        <p>Documents you generate using LandlordAI are yours to use. The LandlordAI platform, branding, and underlying technology remain our property.</p>
        <h2>6. Limitation of Liability</h2>
        <p>LandlordAI is provided "as is." We are not liable for any damages resulting from use of our service, including but not limited to legal disputes, financial losses, or errors in generated content.</p>
        <h2>7. Changes to Terms</h2>
        <p>We may update these terms at any time. Continued use of the service constitutes acceptance of updated terms.</p>
        <h2>8. Contact</h2>
        <p>Questions? Email us at support@landlordai.app</p>
      </div>
    </>
  )
}
